### ISSUE TITLE
sys_sleep doesnt guard against negative delays

### ISSUE THREAD

**Issue by Ryzee119** [AlexOberhofer/SDL2-GNUBoy#8]
If the frame time is longer than framelen, the delay will be negative. See

https://github.com/AlexOberhofer/SDL2-GNUBoy/blob/f4427f2a4f49167f2135e36486812cf0a1bc1420/src/emu.c#L88

sys_sleep in nix and windows dont check this and will hang. I encountered this went disabling sound.

Upsteam does this:
https://github.com/rofl0r/gnuboy/blob/1655356c6430c7c68c3c6071e1a44e3bea5066e9/sys/nix/nix.c#L63

Secondly,

`pcm_submit` always returns 1. This should return 0 if not using sound to fall back to the manual delay
https://github.com/AlexOberhofer/SDL2-GNUBoy/blob/f4427f2a4f49167f2135e36486812cf0a1bc1420/sys/sdl2/sdl-audio.c#L77-L90

Both these fixes need to be implemented to allow disabling sound while maintaining accurate timing

**Comment by AlexOberhofer** [comment]
Do you have recreation steps in how you were getting the application to hang up? It still seems to freeze up when resizing/moving the window when the binary was compiled with the SILENT flag

**Comment by AlexOberhofer** [comment]
Adding an extra check to the system sleep similar to how it was done in upstream allows me to move/resize without hanging the emulation thread... Are there any other use cases I should try before I merge in that fix? See PR #9

**Comment by Ryzee119** [comment]
Normally this wouldnt actually happen as the code always did this manual delay and never returned 0 so the alternate delay loop never was called. If you did disable sound the game just ran really fast.

https://github.com/AlexOberhofer/SDL2-GNUBoy/blob/f4427f2a4f49167f2135e36486812cf0a1bc1420/sys/sdl2/sdl-audio.c#L85

It occurred if you disabled sound and made that function return 0 like its meant to, which made it fallback to the alternative delay:

https://github.com/AlexOberhofer/SDL2-GNUBoy/blob/f4427f2a4f49167f2135e36486812cf0a1bc1420/src/emu.c#L86-L91
